swagger: '2.0'
info:
  title: 1194-URLopen-API
  x-ibm-name: 1194-urlopen-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |
            var urlopen = require('urlopen');

            var options = {
                target: 'http://httpbin.org/get',
                method: 'get',
                contentType: 'text/plain',
                timeout: 60
            };

            urlopen.open(options, function(error, response) {
                if (error) {
                    // Handle HTTP or DNS errors
                    session.output.write("urlopen error: " + JSON.stringify(error));
                } else {
                    var responseStatusCode = response.statusCode;
                    var responseReasonPhrase = response.reasonPhrase;

                    console.log("Response status code: " + responseStatusCode);
                    console.log("Response reason phrase: " + responseReasonPhrase);

                    // Always read the response asynchronously as buffer or text
                    response.readAsBuffer(function(error, responseData) {
                        if (error) {
                            session.output.write("readAsBuffer error: " + JSON.stringify(error));
                        } else {
                            session.output.write(responseData); // Sends back raw response
                        }
                    });
                }
            });
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194-urlopen-api
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
