swagger: '2.0'
info:
  title: 1194-Session-API
  x-ibm-name: 1194-session-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: >
            // Example: Read input JSON, store a value in context variable,
            write a response


            var jsonInput1 = {
              "name": "Shwet",
              "id": 1207
            };


            var jsonInput = JSON.stringify(jsonInput1);


            session.input.readAsJSON(function(error, jsonInput) {
                if (error) {
                    session.output.write({ error: "Invalid JSON input" });
                } else {
                    // Store a field in a context variable
                    var name = jsonInput.name || "Guest";
                    session.name("userName").value = name;

                    // Retrieve context variable
                    var userName = session.name("userName").value;

                    // Write output JSON
                    session.output.write({
                        message: "Hello, " + userName + "!",
                        originalInput: jsonInput
                    });
                }
            });
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194-session-api
paths:
  /:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: body
          schema:
            title: root
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
          in: body
        - name: q
          in: query
          type: integer
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
