swagger: '2.0'
info:
  title: 1194_jsonToSoap_Mapping
  x-ibm-name: 1194_jsontosoap_mapping
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - map:
          inputs:
            input:
              schema:
                type: object
                properties:
                  root:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string
                $$title: input
              variable: request.body
              content: application/json
          outputs:
            output:
              schema:
                $schema: http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  Envelope:
                    type: object
                    properties:
                      Header:
                        type: string
                      Body:
                        type: object
                        properties:
                          root:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                $$title: output
              variable: message.body
              content: application/xml
          actions:
            - set: output.Envelope.Body.root
              from: input.root
            - set: output.Envelope.Body.root.id
              from: input.root.id
            - set: output.Envelope.Body.root.name
              from: input.root.name
          version: 2.1.0
          title: map
          options:
            mapEmulateV4EmptyJSONObject: false
            mapEmulateV4DefaultRequiredProps: false
            mapEnablePostProcessingJSON: false
            mapReferenceLimit: 1
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194_jsontosoap_mapping
paths:
  /:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: body
          schema:
            title: root
            type: object
            properties:
              root:
                $ref: '#/definitions/root'
          in: body
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
definitions:
  root:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
    required:
      - id
      - name
