swagger: '2.0'
info:
  title: 1194TestAPI
  x-ibm-name: 1194testapi
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var apim = require('apim');
             
            var body = apim.getvariable('request.body');
            var aId = body.AADHAARID;
             
            var data = {};
             
            if(!aId||aId=='') {
             
               apim.error("AADHAAR_ID_MISSING", 400, "Aadhaar ID is missing");
            }
            else {
              data = body;
            }
             
            apim.setvariable('message.body', data);
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194testapi/v1
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: body
          required: true
          schema:
            title: root
            type: object
            properties:
              AADHAARID:
                type: integer
          in: body
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
