swagger: '2.0'
info:
  title: 1194_soapToJson
  x-ibm-name: 1194_soaptojson
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - map:
          inputs:
            input:
              schema:
                $schema: http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  Envelope:
                    type: object
                    properties:
                      Header:
                        type: object
                      Body:
                        type: object
                        properties:
                          root:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
              variable: request.body
              content: application/xml
          outputs:
            output:
              schema:
                type: object
                properties:
                  root:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string
              variable: message.body
              content: application/json
          actions:
            - set: output.root
              from: input.Envelope.Body.root
            - set: output.root.id
              from: input.Envelope.Body.root.id
            - set: output.root.name
              from: input.Envelope.Body.root.name
          version: 2.1.0
          title: soapToJsonMap
          options:
            mapEmulateV4EmptyJSONObject: false
            mapEmulateV4DefaultRequiredProps: false
            mapEnablePostProcessingJSON: false
            mapReferenceLimit: 1
  properties:
    target-url:
      value: http://example.com/soap-endpoint
      description: Dummy backend (not used here)
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194_soaptojson
paths:
  /:
    post:
      summary: SOAP to JSON Transformation
      consumes:
        - application/xml
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            title: Envelope
            type: object
            properties: {}
      responses:
        '200':
          description: Successful transformation
          schema:
            type: object
            properties:
              root:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
