swagger: '2.0'
info:
  title: 1194-XmlToJsonUsingMap-API
  x-ibm-name: 1194-xmltojsonusingmap-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - map:
          inputs:
            body:
              schema:
                type: object
                properties:
                  Person:
                    type: object
                    properties:
                      Id:
                        type: integer
                      Name:
                        type: string
                $$title: body
              variable: request.body
              content: application/xml
          outputs:
            output:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                  Name:
                    type: string
                $$title: output
              variable: message.body
              content: application/json
          actions:
            - set: output.Id
              from: body.Person.Id
            - set: output.Name
              from: body.Person.Name
          version: 2.1.0
          title: map
          options:
            mapEmulateV4EmptyJSONObject: false
            mapEmulateV4DefaultRequiredProps: false
            mapEnablePostProcessingJSON: false
            mapReferenceLimit: 1
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /xmltojson
paths:
  /convert:
    post:
      consumes:
        - application/xml
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              Person:
                type: object
                properties:
                  Id:
                    type: integer
                  Name:
                    type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              Id:
                type: integer
              Name:
                type: string
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
