swagger: '2.0'
info:
  title: 1194-Addition_Task-API
  x-ibm-name: 1194-addition_task-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: >+
            var apim = require('apim');


            var value1 =
            parseFloat(apim.getvariable('request.parameters.num1'));

            var value2 =
            parseFloat(apim.getvariable('request.parameters.num2'));


            var result = value1 + value2;


            var message = "Sum of the numbers " + value1 + " and " + value2 + "
            is " + result;


            apim.setvariable('message.body', message);

  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /v2
paths:
  /:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: num1
          in: query
          type: integer
        - name: num2
          in: query
          type: integer
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
