swagger: '2.0'
info:
  title: 1194-ContextObject-API
  x-ibm-name: 1194-contextobject-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var id = context.get('request.parameters.id');

            var result = {
              "name": "Avishkar",
              "id": id.values
            };

            var res = JSON.stringify(result);

            context.set('message.body', res);
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194-contextobject-api
paths:
  /:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: id
          in: query
          type: integer
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
