swagger: '2.0'
info:
  title: 1194_Validate_GatewayScript
  x-ibm-name: 1194_validate_gatewayscript
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |
            var apim = require('apim');

            // Get request body as string
            var body = apim.getvariable('request.body');

            // Extract fields
            var id = body.id;
            var name = body.name;

            // Validate presence
            if (id == null || name == null || !(id) || !(name)) {
              context.message.statusCode = 400;
              session.output.write('Invalid request body: Missing id or name');
            } 
            else {
              if(id > 0 && id <= 9999 && typeof(name) === 'string' && name.length <= 10)
              {
                session.output.write('Request Message validated successfully');
              }
              else{
                context.message.statusCode = 400;
                session.output.write('Validation failed');
              }
              
            }
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194_validate_gatewayscript
paths:
  /:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: body
          schema:
            title: root
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
          in: body
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
