swagger: '2.0'
info:
  title: 1194-CheckCountryCode-API
  x-ibm-name: 1194-checkcountrycode-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var apim = require('apim');
             
            var country = apim.getvariable('request.parameters.country');
             
            if(country !=='IN'){
              apim.setvariable('message.status.code', 403);
              var errorResponse = {
                    "eCode": "403",
                    "eMsg": "Access denied: country not allowed"
              };
              var eRes = JSON.stringify(errorResponse);
              
              apim.setvariable('message.body', eRes);
              return;
            }
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194-checkcountrycode-api
paths:
  /:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: country
          in: query
          type: string
          required: true
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
