swagger: '2.0'
info:
  title: 1194_ValidateXML
  x-ibm-name: 1194_validatexml
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - parse:
          version: 2.2.0
          title: parse
          parse-settings-reference:
            default: apic-default-parsesettings
      - validate:
          version: 2.7.0
          title: validate
          graphql-error-policy: all
          compile-settings: {}
          validate-against: definition
          definition: '#/definitions/Customer'
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /1194_validatexml
schemes:
  - https
paths:
  /new-path:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      parameters:
        - name: body
          required: true
          schema:
            type: object
            properties:
              Customer:
                $ref: '#/definitions/Customer'
          in: body
definitions:
  Customer:
    type: object
    xml:
      name: Customer
    properties:
      Name:
        type: string
        xml:
          name: Name
      Contact:
        type: integer
        xml:
          name: Contact
        minimum: 1000000000
        maximum: 9999999999
    required:
      - Name
      - Contact
