openapi: 3.0.0
info:
  version: 1.0.0
  title: xmlTojson_openAPI_3.0
  x-ibm-name: xmltojson_openapi_3.0
servers:
  - url: /xmltojson_openapi_3.0
x-ibm-configuration:
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - parse:
          version: 2.2.0
          title: parse
          parse-settings-reference:
            default: apic-default-parsesettings
      - xml-to-json:
          version: 2.0.0
          title: xml-to-json
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /:
    post:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/xml:
            schema:
              title: root
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
components:
  securitySchemes:
    clientID:
      type: apiKey
      in: header
      name: X-IBM-Client-Id
security:
  - clientID: []
